import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Matches the config: the API reference exists in the default locale only. */
const IS_DEFAULT_LOCALE =
	(process.env.DOCUSAURUS_CURRENT_LOCALE ?? "en") === "en";

/**
 * Two sidebars: the guide is written by hand and ordered by how someone learns
 * the framework; the API one is generated by TypeDoc from the packages' TSDoc.
 */
const sidebars: SidebarsConfig = {
	guide: [
		"intro",
		"installation",
		"getting-started",
		{
			type: "category",
			label: "Core concepts",
			collapsed: false,
			items: [
				"core/module",
				"core/clients",
				"core/commands",
				"core/listeners",
				"core/context",
				"core/guards-and-filters",
				"core/messaging",
				"core/capabilities",
				"core/structures",
			],
		},
		{
			type: "category",
			label: "Platforms",
			items: [
				"platforms/overview",
				"platforms/whatsapp-web-js",
				"platforms/baileys",
				"platforms/writing-an-adapter",
			],
		},
		{
			type: "category",
			label: "Recipes",
			items: ["packages/dashboard", "packages/webhook", "packages/locale"],
		},
		{
			type: "category",
			label: "Techniques",
			items: ["advanced/connection"],
		},
	],
	...(IS_DEFAULT_LOCALE
		? { api: [{ type: "autogenerated" as const, dirName: "api" }] }
		: {}),
};

export default sidebars;
