name: Continuous Integration

on:
  push:
    branches: [master]
    paths-ignore: [".github/**"]
  pull_request:
    paths-ignore: [".github/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Restore Nx cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/tsconfig.base.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/tsconfig.base.json') }}-

      - name: Run BiomeJS
        run: yarn lint

      - name: Build all packages
        run: yarn build
