export const MESSAGING_OPTIONS = Symbol("NESTWHATS::MESSAGING_OPTIONS");
export const WEBHOOK_SERVICE_TOKEN = Symbol.for("NESTWHATS::WEBHOOK_SERVICE");
export const CLIENT_MANAGER_TOKEN = Symbol.for("NESTWHATS::CLIENT_MANAGER");
